[package]
name = "tet-visulizer-core"
version.workspace = true
edition.workspace = true

[dependencies]
binrw.workspace = true
cgmath = "0.18.0"
ordered-float.workspace = true
rand.workspace = true
strum.workspace = true
strum_macros.workspace = true
three-d.workspace = true
tritet.workspace = true
